In [2]:
import nibabel as nib
import numpy as np
from scipy.ndimage.interpolation import zoom

In [17]:
scan = nib.load("/analysis/ritter/misc/masks/Neuromorphometrics/tpm/labels_Neuromorphometrics.nii")
neuromorph_map = scan.get_data()
nmm_map = np.zeros(shape=(96, 114, 96))

for lbl_idx in np.unique(neuromorph_map):
    print(lbl_idx)
    nmm_map_lbl = neuromorph_map.copy()
    nmm_map_lbl[lbl_idx!=neuromorph_map] = 0
    nmm_map_lbl[lbl_idx==neuromorph_map] = 1
    zoomed_lbl = zoom(nmm_map_lbl, 0.7895, order=0)
    zoomed_lbl[zoomed_lbl!=1] = 0
    nmm_map += zoomed_lbl*lbl_idx
    print(np.unique(nmm_map))

0
(96, 114, 96)
(96, 114, 96)
[0.]
4
(96, 114, 96)
(96, 114, 96)
[0. 4.]
11
(96, 114, 96)
(96, 114, 96)
[ 0.  4. 11.]
23
(96, 114, 96)
(96, 114, 96)
[ 0.  4. 11. 23.]
30
(96, 114, 96)
(96, 114, 96)
[ 0.  4. 11. 23. 30.]
31
(96, 114, 96)
(96, 114, 96)
[ 0.  4. 11. 23. 30. 31.]
32
(96, 114, 96)
(96, 114, 96)
[ 0.  4. 11. 23. 30. 31. 32.]
35
(96, 114, 96)
(96, 114, 96)
[ 0.  4. 11. 23. 30. 31. 32. 35.]
36
(96, 114, 96)
(96, 114, 96)
[ 0.  4. 11. 23. 30. 31. 32. 35. 36.]
37
(96, 114, 96)
(96, 114, 96)
[ 0.  4. 11. 23. 30. 31. 32. 35. 36. 37.]
38
(96, 114, 96)
(96, 114, 96)
[ 0.  4. 11. 23. 30. 31. 32. 35. 36. 37. 38.]
39
(96, 114, 96)
(96, 114, 96)
[ 0.  4. 11. 23. 30. 31. 32. 35. 36. 37. 38. 39.]
40
(96, 114, 96)
(96, 114, 96)
[ 0.  4. 11. 23. 30. 31. 32. 35. 36. 37. 38. 39. 40.]
41
(96, 114, 96)
(96, 114, 96)
[ 0.  4. 11. 23. 30. 31. 32. 35. 36. 37. 38. 39. 40. 41.]
44
(96, 114, 96)
(96, 114, 96)
[ 0.  4. 11. 23. 30. 31. 32. 35. 36. 37. 38. 39. 40. 41. 44.]
45
(96, 114, 96)
(96, 114, 96)

(96, 114, 96)
(96, 114, 96)
[  0.   4.  11.  23.  30.  31.  32.  35.  36.  37.  38.  39.  40.  41.
  44.  45.  46.  47.  48.  49.  50.  51.  52.  55.  56.  57.  58.  59.
  60.  61.  62.  63.  64.  69.  71.  72.  73.  75.  76. 100. 101. 102.
 103. 104. 105. 106. 107. 108. 109. 112. 113. 114. 115. 116. 117. 118.
 119.]
120
(96, 114, 96)
(96, 114, 96)
[  0.   4.  11.  23.  30.  31.  32.  35.  36.  37.  38.  39.  40.  41.
  44.  45.  46.  47.  48.  49.  50.  51.  52.  55.  56.  57.  58.  59.
  60.  61.  62.  63.  64.  69.  71.  72.  73.  75.  76. 100. 101. 102.
 103. 104. 105. 106. 107. 108. 109. 112. 113. 114. 115. 116. 117. 118.
 119. 120.]
121
(96, 114, 96)
(96, 114, 96)
[  0.   4.  11.  23.  30.  31.  32.  35.  36.  37.  38.  39.  40.  41.
  44.  45.  46.  47.  48.  49.  50.  51.  52.  55.  56.  57.  58.  59.
  60.  61.  62.  63.  64.  69.  71.  72.  73.  75.  76. 100. 101. 102.
 103. 104. 105. 106. 107. 108. 109. 112. 113. 114. 115. 116. 117. 118.
 119. 120. 121.]
122
(96, 114, 96)
(9

[  0.   4.  11.  23.  30.  31.  32.  35.  36.  37.  38.  39.  40.  41.
  44.  45.  46.  47.  48.  49.  50.  51.  52.  55.  56.  57.  58.  59.
  60.  61.  62.  63.  64.  69.  71.  72.  73.  75.  76. 100. 101. 102.
 103. 104. 105. 106. 107. 108. 109. 112. 113. 114. 115. 116. 117. 118.
 119. 120. 121. 122. 123. 124. 125. 128. 129. 132. 133. 134. 135. 136.
 137. 138. 139. 140. 141. 142. 143. 144. 145. 146.]
147
(96, 114, 96)
(96, 114, 96)
[  0.   4.  11.  23.  30.  31.  32.  35.  36.  37.  38.  39.  40.  41.
  44.  45.  46.  47.  48.  49.  50.  51.  52.  55.  56.  57.  58.  59.
  60.  61.  62.  63.  64.  69.  71.  72.  73.  75.  76. 100. 101. 102.
 103. 104. 105. 106. 107. 108. 109. 112. 113. 114. 115. 116. 117. 118.
 119. 120. 121. 122. 123. 124. 125. 128. 129. 132. 133. 134. 135. 136.
 137. 138. 139. 140. 141. 142. 143. 144. 145. 146. 147.]
148
(96, 114, 96)
(96, 114, 96)
[  0.   4.  11.  23.  30.  31.  32.  35.  36.  37.  38.  39.  40.  41.
  44.  45.  46.  47.  48.  49.  50.  51.  52. 

(96, 114, 96)
(96, 114, 96)
[  0.   4.  11.  23.  30.  31.  32.  35.  36.  37.  38.  39.  40.  41.
  44.  45.  46.  47.  48.  49.  50.  51.  52.  55.  56.  57.  58.  59.
  60.  61.  62.  63.  64.  69.  71.  72.  73.  75.  76. 100. 101. 102.
 103. 104. 105. 106. 107. 108. 109. 112. 113. 114. 115. 116. 117. 118.
 119. 120. 121. 122. 123. 124. 125. 128. 129. 132. 133. 134. 135. 136.
 137. 138. 139. 140. 141. 142. 143. 144. 145. 146. 147. 148. 149. 150.
 151. 152. 153. 154. 155. 156. 157. 160. 161. 162. 163. 164. 165. 166.]
167
(96, 114, 96)
(96, 114, 96)
[  0.   4.  11.  23.  30.  31.  32.  35.  36.  37.  38.  39.  40.  41.
  44.  45.  46.  47.  48.  49.  50.  51.  52.  55.  56.  57.  58.  59.
  60.  61.  62.  63.  64.  69.  71.  72.  73.  75.  76. 100. 101. 102.
 103. 104. 105. 106. 107. 108. 109. 112. 113. 114. 115. 116. 117. 118.
 119. 120. 121. 122. 123. 124. 125. 128. 129. 132. 133. 134. 135. 136.
 137. 138. 139. 140. 141. 142. 143. 144. 145. 146. 147. 148. 149. 150.
 151. 152. 153. 

(96, 114, 96)
(96, 114, 96)
[  0.   4.  11.  23.  30.  31.  32.  35.  36.  37.  38.  39.  40.  41.
  44.  45.  46.  47.  48.  49.  50.  51.  52.  55.  56.  57.  58.  59.
  60.  61.  62.  63.  64.  69.  71.  72.  73.  75.  76. 100. 101. 102.
 103. 104. 105. 106. 107. 108. 109. 112. 113. 114. 115. 116. 117. 118.
 119. 120. 121. 122. 123. 124. 125. 128. 129. 132. 133. 134. 135. 136.
 137. 138. 139. 140. 141. 142. 143. 144. 145. 146. 147. 148. 149. 150.
 151. 152. 153. 154. 155. 156. 157. 160. 161. 162. 163. 164. 165. 166.
 167. 168. 169. 170. 171. 172. 173. 174. 175. 176. 177. 178. 179. 180.
 181. 182.]
183
(96, 114, 96)
(96, 114, 96)
[  0.   4.  11.  23.  30.  31.  32.  35.  36.  37.  38.  39.  40.  41.
  44.  45.  46.  47.  48.  49.  50.  51.  52.  55.  56.  57.  58.  59.
  60.  61.  62.  63.  64.  69.  71.  72.  73.  75.  76. 100. 101. 102.
 103. 104. 105. 106. 107. 108. 109. 112. 113. 114. 115. 116. 117. 118.
 119. 120. 121. 122. 123. 124. 125. 128. 129. 132. 133. 134. 135. 136.
 137.

(96, 114, 96)
(96, 114, 96)
[  0.   4.  11.  23.  30.  31.  32.  35.  36.  37.  38.  39.  40.  41.
  44.  45.  46.  47.  48.  49.  50.  51.  52.  55.  56.  57.  58.  59.
  60.  61.  62.  63.  64.  69.  71.  72.  73.  75.  76. 100. 101. 102.
 103. 104. 105. 106. 107. 108. 109. 112. 113. 114. 115. 116. 117. 118.
 119. 120. 121. 122. 123. 124. 125. 128. 129. 132. 133. 134. 135. 136.
 137. 138. 139. 140. 141. 142. 143. 144. 145. 146. 147. 148. 149. 150.
 151. 152. 153. 154. 155. 156. 157. 160. 161. 162. 163. 164. 165. 166.
 167. 168. 169. 170. 171. 172. 173. 174. 175. 176. 177. 178. 179. 180.
 181. 182. 183. 184. 185. 186. 187. 190. 191. 192. 193. 194. 195. 196.
 197. 198. 199.]
200
(96, 114, 96)
(96, 114, 96)
[  0.   4.  11.  23.  30.  31.  32.  35.  36.  37.  38.  39.  40.  41.
  44.  45.  46.  47.  48.  49.  50.  51.  52.  55.  56.  57.  58.  59.
  60.  61.  62.  63.  64.  69.  71.  72.  73.  75.  76. 100. 101. 102.
 103. 104. 105. 106. 107. 108. 109. 112. 113. 114. 115. 116. 117. 118.


In [18]:
output_map = nib.Nifti1Image(nmm_map, scan.affine)
nib.save(output_map, "/analysis/fabiane/scaled_nmm_order0_again.nii")

In [9]:
scan = nib.load("/analysis/fabiane/atlases/JHU/JHU-ICBM-labels-1mm.nii.gz")
atlas_map = scan.get_data()
atl_map = np.zeros(shape=(96, 114, 96))

for lbl_idx in np.unique(atlas_map):
    print(lbl_idx)
    atl_map_lbl = atlas_map.copy()
    atl_map_lbl[lbl_idx!=atlas_map] = 0
    atl_map_lbl[lbl_idx==atlas_map] = 1
    zoomed_lbl = zoom(atl_map_lbl, 0.525, order=0)
    zoomed_lbl[zoomed_lbl!=1] = 0
    atl_map += zoomed_lbl*lbl_idx
    print(np.unique(atl_map))

0
[0.]
1


/home/fabiane/.local/lib/python3.6/site-packages/scipy/ndimage/interpolation.py:583: UserWarning: From scipy 0.13.0, the output shape of zoom() is calculated with round() instead of int() - for these inputs the size of the returned array has changed.
  "the returned array has changed.", UserWarning)


[0. 1.]
2
[0. 1. 2.]
3
[0. 1. 2. 3.]
4
[0. 1. 2. 3. 4.]
5
[0. 1. 2. 3. 4. 5.]
6
[0. 1. 2. 3. 4. 5. 6.]
7
[0. 1. 2. 3. 4. 5. 6. 7.]
8
[0. 1. 2. 3. 4. 5. 6. 7. 8.]
9
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
10
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
11
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
12
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
13
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13.]
14
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]
15
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]
16
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16.]
17
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.]
18
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18.]
19
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]
20
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20.]
21
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9

In [11]:
output_map = nib.Nifti1Image(atl_map, scan.affine)
nib.save(output_map, "/analysis/fabiane/scaled_JHU_WM_order0.nii")